# Generated by Django 2.2.4 on 2019-09-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_discourse_connector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discourseclient',
            name='callback_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discourseclient',
            name='api_username',
            field=models.CharField(default='system', max_length=255),
        ),
    ]
